### ISSUE TITLE
PS1-files for some functions exported using Export-Function does not work

### ISSUE THREAD

**Issue by janegilring** [PowerShellModules/PesterHelpers#1]
I used Export-Function to extract 62 functions from a module. It worked fine for all except 5 functions which failed due to various errors I resolved manually:

`
PS [1]: Import-Module MyCoreTools -Force
At C:\Users\username\Documents\WindowsPowerShell\Modules\MyCoreTools\Functions\G
et\Get-PappaPerm.ps1:5 char:26
-     $EndDate = [datetime]â€2016-08-01 08:00â€
-                          ~~~~~~~~~~~~~
  Unexpected token 'â€2016-08-01' in expression or statement.
  - CategoryInfo          : ParserError: (:) [], ParseException
  - FullyQualifiedErrorId : UnexpectedToken

At C:\Users\username\Documents\WindowsPowerShell\Modules\MyCoreTools\Functions\G
et\Get-RebootHistory.ps1:10 char:5
-     '@
-     ~~
  White space is not allowed before the string terminator.
  At C:\Users\username\Documents\WindowsPowerShell\Modules\MyCoreTools\Functions\G
  et\Get-RebootHistory.ps1:1 char:28
- function Get-RebootHistory {
-                            ~
  Missing closing '}' in statement block or type definition.
  - CategoryInfo          : ParserError: (:) [], ParseException
  - FullyQualifiedErrorId : WhitespaceBeforeHereStringFooter

At C:\Users\username\Documents\WindowsPowerShell\Modules\MyCoreTools\Functions\O
ut\Out-OneNote.ps1:97 char:5
-     "@
-     ~~
  White space is not allowed before the string terminator.
  At C:\Users\username\Documents\WindowsPowerShell\Modules\MyCoreTools\Functions\O
  ut\Out-OneNote.ps1:1 char:22
- function Out-OneNote {
-                      ~
  Missing closing '}' in statement block or type definition.
  - CategoryInfo          : ParserError: (:) [], ParseException
  - FullyQualifiedErrorId : WhitespaceBeforeHereStringFooter

At C:\Users\username\Documents\WindowsPowerShell\Modules\MyCoreTools\Functions\R
esize\Resize-Console.ps1:54 char:48
- ...         $MainWindowHandle = (Get-Process â€“id $pid).MainWindowHandle
-                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~
  The string is missing the terminator: ".
  At C:\Users\username\Documents\WindowsPowerShell\Modules\MyCoreTools\Functions\R
  esize\Resize-Console.ps1:92 char:1
- 
  Missing closing ')' in expression.
  At C:\Users\username\Documents\WindowsPowerShell\Modules\MyCoreTools\Functions\R
  esize\Resize-Console.ps1:46 char:104
- ... ame -eq 'Maximize') -or ($PSCmdlet.ParameterSetName -eq 'Restore')) {
-                                                                         ~
  Missing closing '}' in statement block or type definition.
  At C:\Users\username\Documents\WindowsPowerShell\Modules\MyCoreTools\Functions\R
  esize\Resize-Console.ps1:1 char:25
- function Resize-Console {
-                         ~
  Missing closing '}' in statement block or type definition.
  - CategoryInfo          : ParserError: (:) [], ParseException
  - FullyQualifiedErrorId : TerminatorExpectedAtEndOfString 
    `

Maybe related to encoding issues?

**Comment by kilasuit** [comment]
This should now be fixed in the latest release available from the PSGallery

**Comment by janegilring** [comment]
Confirmed
