### ISSUE TITLE
Export-Function should support pipeline input

### ISSUE THREAD

**Issue by janegilring** [PowerShellModules/PesterHelpers#2]
Currently we need to use foreach in order to export functions using Export-Function:
`Get-Command -Module MyModyle | Where-Object commandtype -eq 'Function' | foreach {
Export-Function -OutPath C:\temp\MyCoreToolsExported3\ -Function $_.Name
}`

It would be more convenient to be able to use pipeline input like this:
`Get-Command -Module MyModyle | Where-Object commandtype -eq 'Function' | 
Export-Function -OutPath C:\temp\MyCoreToolsExported3\`

**Comment by kilasuit** [comment]
I'm thinking of implementing a Export-ModuleFunction function that would essentially be a wrapper for 

``` powershell
Get-Command -Module MyModyle | Where-Object commandtype -eq 'Function' | foreach { Export-Function -OutPath C:\temp\MyModule\ -Function $_.Name }
```

However I think that Pipeline input would also be useful too so will look to add in this support too.
