### ISSUE TITLE
Export-Function -OutPath should not need a trailing slash

### ISSUE THREAD

**Issue by janegilring** [PowerShellModules/PesterHelpers#3]
When specifying a folder path to Export-Function -OutPath the folder structure created is not as expected when the path does not end with a slash. Pester tests is created in separate subfolders under the root directory if a \ is not specified at the end of the path.

Export-Function -OutPath C:\temp\ works as expected.
Export-Function -OutPath C:\temp does not work as expected.

**Comment by kilasuit** [comment]
I've reproduced this and will get this fixed and an update released later today
